[[Xorg_libpthread_stubs]]
arch = "armv7l"
git-tree-sha1 = "f82a440e5bfcdf9f52ffc41f4295ec9dc0cc27ed"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "fd77e669ba00c176ed221bf45eb1de0fa840aeb4e5eaa1a0d07f7a06d1d3309b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "i686"
git-tree-sha1 = "ca15ffd7071b6898208ae0d460a549c2a6f44d80"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "b215e6312b361ee53d58f6da7b9e357fc46d2126012add9032b3412d00a4fe67"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.i686-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "aarch64"
git-tree-sha1 = "f791fc8d83a9489a239fcdab4663486e6f772b55"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "8fb5051bcb3f416da66d289767f7144521188b1a504b16c9af765686b937d97e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "armv7l"
git-tree-sha1 = "46796ee3da5c6d6347a90dd7c2532bbdc46abffc"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "d7ec54de711d57da8b0c638193e32283aa5a67cbee9ffe3b0288270e7bcb607b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "aarch64"
git-tree-sha1 = "0d2868e9b18a5ca88de8e1600b51b39a91441820"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "4af9a96ffab8ae31e05770f01dbd2bfb63fe37bad0633877a3a315ab3693fb26"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.aarch64-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "d676e3dcf92922f9cea3e750a3cab11b43f35329"
os = "freebsd"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "07571ae3861c7e53956435727f30512be9a09baf2aafb591128b4caca90f55a9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "i686"
git-tree-sha1 = "3a3eae82484f2ff1c08abbdc4e4ec6e71ce3dc9e"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "bb999d2beb4716441e40007a134dbda8ff3ef10244d68c34b255876634bc1e4b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.i686-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "8a2317207c924b07b1ced637a13102ba921df270"
libc = "musl"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "a1c817bbd0bb5609c928b556bc5578b6b966ed040d4a80be4f47974b7b78d892"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.x86_64-linux-musl.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "x86_64"
git-tree-sha1 = "ca41ad8b14a53df6be9a2798ab6a981f30b4b2aa"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "dfd06b6be3bd9bb06fb6298ec3d0cc0b32e06e89f5adef6a9361de243db2e496"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libpthread_stubs]]
arch = "powerpc64le"
git-tree-sha1 = "8d2df725ed1c41b7a9b549d5033ae954bb12c37b"
libc = "glibc"
os = "linux"

    [[Xorg_libpthread_stubs.download]]
    sha256 = "5d44a360520e66b52390beebe590cd3240539673bd84d3d77401130e6c6b49fa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpthread_stubs_jll.jl/releases/download/Xorg_libpthread_stubs-v0.1.0+1/Xorg_libpthread_stubs.v0.1.0.powerpc64le-linux-gnu.tar.gz"
